### ISSUE TITLE
ZED双目相机无法连接

### ISSUE THREAD

**Issue by qgli** [Katzeee/Notes#1]
感谢大佬的分享，我按你教程在内核添加多媒体支持之后挂载usb相机依旧无法识别，请问可能在内核需要添加什么其他的驱动吗？

**Comment by Katzeee** [comment]
你可以试试多选一些`Multimedia support`下边的选项，根据摄像头厂家的不同会对应不同类型的驱动。我不是很清楚针对某种特定摄像头应该选取哪些驱动，当时我也是在多次尝试之后找到了适合我的驱动。

**Comment by qgli** [comment]
更新一下，按照这个教程的最后一步 ’sudo chmod 777 /dev/video* ‘ 加了权限之后，普通单目webcam可以工作，但是zed依旧不行...

**Comment by qgli** [comment]
再次补充，需要每次插拔usb都要加入这个权限设置才可以，目前zed的影像功能可以驱动，但是zed sdk中深度估计等api均无法使用，这个可能跟wsl2下一堆bug的cuda功能有关。

**Comment by Katzeee** [comment]
权限是这样的，每次你插入之后对于linux来说都是一个新的文件，他的权限是需要再次设置的。api无法使用你可以再分析一下问题，如果是cuda导致的你只需要将cuda关闭（api文档中应该会告诉你在哪有cuda选项）采用cpu来进行计算那api应该还是可以正常使用的，说到底还是环境的问题。我没有再wsl下用过cuda，所以不是很清楚。
